version: "3.7"
services:
  dev_db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: goxygen
      MYSQL_USER: goxygen
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
