version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      profile: prod
      db_pass: pass
  db:
    image: mysql:8.0.23
    container_name: db
    environment:
      MYSQL_DATABASE: goxygen
      MYSQL_USER: goxygen
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql