theme: minima

social:
  twitter: https://twitter.com/sashashpota
  github: https://github.com/shpota
  linkedin: https://www.linkedin.com/in/shpota
minima:
  social_links:
    twitter: https://twitter.com/sashashpota
    github: https://github.com/shpota
    linkedin: https://www.linkedin.com/in/shpota